import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from '@/components/Navigation'

import {Poppins} from '@next/font/google'
const poppins = Poppins({
  subsets:['latin'],
  weight:['400','700']
})

export const metadata: Metadata = {
  title: "Finance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
