'use client'

import localFont from "next/font/local";
import "./globals.css";
import Nav from '@/components/Navigation'
import FinanceContextProvider from '@/lib/store/finance-context'
import {Poppins} from '@next/font/google'
const poppins = Poppins({
  subsets:['latin'],
  weight:['400','700']
})

const metadata = {
  title: "Finance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <FinanceContextProvider>
        <Nav />
        {children}
        </FinanceContextProvider>
    
      </body>
    </html>
  );
}
